import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Provider from "./components/provider";
import { getServerSession } from "next-auth";

const inter = Roboto({ subsets: ["cyrillic"], weight: ["100"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider session={session}>
          <main
            className="bg-slate-100 
          max-w-full max-h-screen h-screen w-screen
          text-black 
          ">
            {children}
          </main>
        </Provider>
      </body>
    </html>
  );
}
